### PR TITLE
chore: Update the Readme for project

### PR DESCRIPTION
**Pull request by farhaanbukhsh**
This updates the Readme of the project

~~**Discussions**: Link to any public dicussions about this PR or the design/architecture. Otherwise omit this.~~

**Dependencies**: None

**Screenshots**: Always include screenshots if there is any change to the UI.

~~**Sandbox URL**: TBD - sandbox is being provisioned.~~

**Merge deadline**: "None" 

**Testing instructions**:

None

**Author notes and concerns**:
None

**Reviewers**
- [ ] @connorhaugh 

Fixes: <>
Co-authored-by: <>
Private-ref: Part of https://tasks.opencraft.com/browse/BB-6582

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @farhaanbukhsh!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by connorhaugh** [comment]
Thanks so much @farhaanbukhsh !

**Comment by farhaanbukhsh** [comment]
> Thanks so much @farhaanbukhsh !

Thanks a lot for reviewing, can we merge this in?

**Comment by openedx-webhooks** [comment]
@farhaanbukhsh 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/frontend-lib-content-components&entry.867055334=https://github.com/edx/frontend-lib-content-components/pull/98&entry.1484655318=https://github.com/farhaanbukhsh&entry.752974735=2022-08-11+19:17&entry.1917517419=2022-08-17+15:13&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
