### PR TITLE
feat: add simple code block and blockquote buttons

### PR DESCRIPTION
**Pull request by connorhaugh**
adresses
https://2u-internal.atlassian.net/browse/TNL-9836
and 
https://2u-internal.atlassian.net/browse/TNL-9936

### CODE REVIEW

**Review by rayzhou-bit — CHANGES_REQUESTED** [review]
I tested this out using the www gallery.

- Add image button works great!
- I couldn't get the edit image button to appear.
- Blockquote looks great!
- Code block button isn't highlighted the same way blockquote is when the cursor is in code block content. This behavior is the same as the old editor. So my question is should this behavior remain?

**Review by kenclary — APPROVED** [review]
nice.

**Comment by connorhaugh** [comment]
@rayzhou-bit 
> I tested this out using the www gallery.
Just to note, I have run on devstack as well and it is working.

> * I couldn't get the edit image button to appear.
 I have added that functionality back in see the attached screenshot
Screen Shot 2022-05-24 at 9 37 15 AM

> * Code block button isn't highlighted the same way blockquote is when the cursor is in code block content. This behavior is the same as the old editor. So my question is should this behavior remain?
Yeah this is a symptom of <code> being an inline html element, instead of a block element. I don't want to rewrite the whole Tinymce html formatter we got for free, and making a custom block format will make things worse.

**Comment by connorhaugh** [comment]
@rayzhou-bit  headed out soon but would love your thoughts on my changes tysm.

**Comment by rayzhou-bit** [comment]
I tested the changes and it looks good to me!

**Review by rayzhou-bit — APPROVED** [review]

**Pull request merged**
